name: Vercel CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Turbo prune
      run: npx turbo prune --scope=web

    - name: Install dependencies
      run: npm ci
      working-directory: ./out

    - name: Build project
      run: npm run build
      working-directory: ./out/apps/web
      env:
        NEXT_PUBLIC_APP_URL: https://${{ vars.DOMAIN }}

    - name: Deploy to Vercel
      run: npx vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
      working-directory: ./out/apps/web
      env:
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}